# Generated by Django 4.2.9 on 2024-05-23 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.TextField(blank=True, null=True)),
                ('bank_code', models.TextField(blank=True, null=True)),
                ('bank', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('start', models.TextField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='like_deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('intr_type', models.CharField(max_length=5)),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('rsrv_type_nm', models.TextField(blank=True, null=True)),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.deposit')),
            ],
        ),
    ]
